---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - klock.rnemet.dev
  resources:
  - locks
  verbs:
  - get
  - list
  - watch
