apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klock-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klock-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klock-manager-role
rules:
- apiGroups:
  - klock.rnemet.dev
  resources:
  - locks
  verbs:
  - get
  - list
  - watch