apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: klock-controller-manager-metrics-service
  namespace: klock-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: klock-webhook-service
  namespace: klock-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager